[build]
  command = "pnpm build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Untuk netlify dev
[dev]
  command = "pnpm run dev"
  targetPort = 3000          # Ubah kalau port Express kamu bukan 3000
  port = 8888
  framework = "#custom"

# Redirect untuk production
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200